<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Url' => 'Url',
    'Title' => 'Title',
    'Content' => 'Content',
    'Markdown Content' => 'Markdown Content',
    'Status' => 'Status',
    'Meta Title' => 'Meta Title',
    'Meta Description' => 'Meta Description',
    'Meta Keywords' => 'Meta Keywords',
    'Comments available' => 'Comments available',
    'Date Created' => 'Date Created',
    'Date Updated' => 'Date Updated',
    'Are comments available on the page?' => 'Are comments available on the page?',
    'This one accepts only letters, numbers, dash and slash, i.e. "docs/installation".' => 'This one accepts only letters, numbers, dash and slash, i.e. "docs/installation".',
    'Create' => 'Create',
    'Update' => 'Update',
    'Delete' => 'Delete',
    'Go Back' => 'Go Back',
    'Enabled' => 'Enabled',
    'Disabled' => 'Disabled',
    'Update Page: {0}' => 'Update Page: {0}',
    'Cms Pages' => 'Cms Pages',
    'Create Page' => 'Create Page',
    'View Comments' => 'View Comments',
    'Select Status' => 'Select Status',
    'Select' => 'Select',
    'Actions' => 'Actions',
    'Page has been created.' => 'Page has been created.',
    'Page has been updated.' => 'Page has been updated.',
    'Page has been deleted.' => 'Page has been deleted.',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'File Extension' => 'File Extension',
    'File Version' => 'File Version',
];
